# Generated by Django 5.2.12 on 2026-03-18 05:10

import apps.mapping.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('csv_to_json', 'CSV to JSON'), ('json_to_csv', 'JSON to CSV')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.FileField(upload_to=apps.mapping.models.input_upload_path)),
                ('input_filename', models.CharField(max_length=255)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=apps.mapping.models.output_upload_path)),
                ('output_filename', models.CharField(blank=True, default='', max_length=255)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('rows_processed', models.IntegerField(default=0)),
                ('columns_count', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
