# Generated by Django 5.2.12 on 2026-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='function_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='transform_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='direction',
            field=models.CharField(choices=[('json_to_csv', 'JSON to CSV')], max_length=20),
        ),
    ]
